---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "OpenStack projects, users and domains"
subcategory: "Guides"
description: |-
  How the OpenStack identity resources pick an OpenStack domain, what domain_id does, and what to expect from projects that cannot be deleted.
---

# OpenStack projects, users and domains

The `cleura_openstack_*` resources and data sources manage OpenStack (Keystone) identity
objects in your Cleura account: **projects**, **users**, and a user's **roles on a project**.
They are account-level objects, so the provider needs only credentials and a `region`;
`project_id` on the provider is not required.

```terraform
provider "cleura" {
  cloud  = "public"
  region = "Sto2"
}

resource "cleura_openstack_project" "sandbox" {
  name = "team-sandbox"
}

resource "cleura_openstack_user" "ci" {
  name                = "ci-deployer"
  password            = var.ci_password # write-only, Terraform 1.11+
  password_wo_version = "1"
}

resource "cleura_openstack_role_assignment" "ci_sandbox" {
  user_id    = cleura_openstack_user.ci.id
  project_id = cleura_openstack_project.sandbox.id
  roles      = ["member"]
}
```

## Domains: what they are and how the provider picks one

In OpenStack every project and user lives in a **domain**. A Cleura account has **one domain
per region**: one for `Sto2`, one for `Kna1`, one for `Fra1`, and so on. All of them carry the
same display name (for example `CCP_Domain_44931`), so only the domain **ID** tells them apart.
Every OpenStack identity call in the Cleura API is addressed to a domain ID.

You normally never see this. **The provider derives the domain from the provider's `region`**:

1. It lists the account's domains once per Terraform run and picks the domain whose area
   serves the configured `region` (the region tag is matched case-insensitively).
2. If the account has exactly one domain, that domain is used regardless of region.
3. The chosen domain is recorded in the resource's computed `domain_id` attribute, so it is
   visible in state and in `terraform show`.

So with `region = "Sto2"`, projects and users are created in the Stockholm domain, and a
provider configured for `Fra1` manages the Frankfurt domain. Because a project or user
cannot move between domains, `domain_id` **forces replacement** when it changes.

### When to set `domain_id` yourself

Every `cleura_openstack_*` resource and data source has an optional `domain_id`. Set it only
when:

- the provider reports that **no domain** or **more than one domain** serves the region. The
  error lists the candidate IDs; pick one and set it explicitly.
- you want to manage objects in **another region's domain** than the provider's `region`
  without a second provider configuration.

Find domain IDs with the cleura CLI:

```shell
cleura openstack domain list
```

For `cleura_openstack_role_assignment`, the user and the project must be in the **same**
domain (the one the resource resolves or you set).

## Projects cannot be deleted

Cleura projects are **never deleted**; disabling them is how Cleura retires a project. The
provider follows that:

- `terraform plan` warns **"Project creation is irreversible"** before a project is created.
- `terraform destroy` **disables** the project (`enabled = false`), removes it from state, and
  warns. The disabled project remains in Cleura and **still counts toward your account's project
  quota**. Re-enable it from the Cleura Cloud control panel, or `terraform import` it again with
  `enabled = true`.

Create projects deliberately, and prefer disabling and re-enabling a project over destroying
and recreating it.

## Reads can lag behind writes

The Cleura API's project and role listings can take **minutes** to reflect a change, and two
consecutive reads may briefly disagree. Consequences you may notice:

- A `terraform plan` right after an `apply` can show the change you just applied as pending
  again. Wait a few minutes and plan again; re-applying is harmless.
- The provider waits for role revocations to settle (up to 60 seconds) before an apply
  finishes, but a plan run immediately afterwards may still list a revoked role.

Only projects the provider's API user can access are listed, so a project created by another
account user is not visible; the provider keeps the last known state and warns instead of
recreating it.

## Where to go next

- [`cleura_openstack_project`](../resources/openstack_project.md) resource and
  [data source](../data-sources/openstack_project.md)
- [`cleura_openstack_user`](../resources/openstack_user.md) resource and
  [data source](../data-sources/openstack_user.md)
- [`cleura_openstack_role_assignment`](../resources/openstack_role_assignment.md)
