package provider

// shootAttributeDescriptions holds MarkdownDescription text for every
// cleura_gardener_shoot attribute, keyed by dotted path (the empty key is the
// resource-level description). The generated schema (resource_gardener_shoot,
// DO NOT EDIT) ships without descriptions, so these are injected onto a copy
// by the Schema wrapper (see withShootDescriptions).
var shootAttributeDescriptions = map[string]string{
	"":                            "Manages a Gardener-managed Kubernetes cluster (a \"shoot\") on Cleura public cloud. Region and project_id come from the provider configuration (never from the cleura CLI). Cluster-shaping attributes fixed at creation — `name`, `enable_ha_control_plane` (only when disabled), `networking.type`, and the `shoot_provider` load-balancer and infrastructure settings — force a full destroy-and-recreate when changed, losing all worker nodes, workloads, and data. `kubernetes_version`, worker groups, `maintenance`, `hibernation_schedules`, `allowed_cidrs`, and Cilium settings are applied in place. Import an existing cluster with its shoot name.",
	"allowed_cidrs":               "List of CIDR blocks permitted to reach the cluster's Kubernetes API server. Optional and Computed: if omitted, the API's current allowlist is read back into state. Applied in place (no replacement).",
	"cloud_profile_name":          "Read-only (Computed). Name of the Gardener CloudProfile the cluster was created against; assigned by the API and written back to state.",
	"enable_ha_control_plane":     "Bool. Whether the Kubernetes control plane runs in high-availability mode. Optional and Computed (the API sets it when omitted). Enabling it is applied in place; disabling it (true → false) forces the cluster to be recreated.",
	"hibernation_schedules":       "Optional and Computed list of automated hibernation windows that scale the cluster down and back up on a schedule. Omit to leave hibernation unmanaged (current schedules are read back into state). Applied in place.",
	"hibernation_schedules.start": "Required. Cron expression (UTC) for when the cluster hibernates, e.g. \"0 20 * * 1-5\". Standard 5–7 field cron; @-shortcuts (@daily, @every 1h, ...) are also accepted. NOTE: cron format, unlike the HHMMSS+ZZZZ used by maintenance.time_window.",
	"hibernation_schedules.end":   "Required. Cron expression (UTC) for when the cluster wakes from hibernation, e.g. \"0 8 * * 1-5\". Same cron syntax as start.",
	"kubernetes_version":          "Required. Target Kubernetes version (numeric, dot-separated), e.g. \"1.35.6\". Applied IN PLACE on change (sent in the edit request) — NOT a replacement. Downgrades are rejected by the API.",
	"maintenance":                 "Optional and Computed maintenance settings (auto-update behavior and the daily maintenance time window). If omitted, Gardener assigns defaults that are read back into state. Applied in place.",
	"maintenance.auto_update":     "Optional and Computed. Controls whether Gardener automatically applies patch updates during the maintenance window.",
	"maintenance.auto_update.kubernetes_version":                        "Bool, Optional and Computed. When true, Kubernetes patch versions are auto-updated during the maintenance window.",
	"maintenance.auto_update.machine_image_version":                     "Bool, Optional and Computed. When true, worker node machine-image versions are auto-updated during the maintenance window.",
	"maintenance.time_window":                                           "Optional and Computed. Daily window during which automatic maintenance runs.",
	"maintenance.time_window.begin":                                     "Required. Window start as HHMMSS+ZZZZ — six-digit 24-hour time plus a four-digit UTC offset, e.g. \"020000+0000\" (02:00:00 UTC). This format differs from the cron used by hibernation_schedules.",
	"maintenance.time_window.end":                                       "Required. Window end in the same HHMMSS+ZZZZ format, e.g. \"060000+0000\".",
	"name":                                                              "Required. Cluster (shoot) name: 1–15 characters of letters, digits, and hyphens. Also the import ID. Changing it forces the cluster to be recreated.",
	"networking":                                                        "Optional and Computed cluster networking configuration (CNI type, Cilium options, and the computed node CIDR). If omitted, the API's networking is read back into state. `type` is immutable; only `cilium_provider_config` is editable in place.",
	"networking.type":                                                   "CNI plugin: one of \"calico\" or \"cilium\". Optional and Computed (API default read back if omitted). Immutable — changing it forces the cluster to be recreated.",
	"networking.nodes":                                                  "Read-only (Computed). Node network CIDR assigned by the API and written back to state.",
	"networking.cilium_provider_config":                                 "Optional and Computed Cilium CNI tuning. Only valid when networking.type = \"cilium\" (rejected at plan time otherwise). Applied in place.",
	"networking.cilium_provider_config.debug":                           "Bool, Optional and Computed. Enables Cilium debug logging.",
	"networking.cilium_provider_config.encryption_enabled":              "Bool, Optional and Computed. Enables Cilium transparent encryption.",
	"networking.cilium_provider_config.encryption_mode":                 "String, Optional and Computed. Encryption backend; only \"wireguard\" is allowed.",
	"networking.cilium_provider_config.encryption_node_to_node_enabled": "Bool, Optional and Computed. Enables node-to-node encryption.",
	"networking.cilium_provider_config.encryption_strict_mode_enabled":  "Bool, Optional and Computed. Enables strict-mode encryption (drops unencrypted traffic).",
	"networking.cilium_provider_config.hubble_enabled":                  "Bool, Optional and Computed. Enables the Hubble network observability layer.",
	"networking.cilium_provider_config.policy_audit_mode":               "Bool, Optional and Computed. Runs network policies in audit-only mode (log, don't enforce).",
	"networking.cilium_provider_config.tunnel":                          "String, Optional and Computed. Datapath tunneling mode; one of \"vxlan\", \"geneve\", or \"disabled\".",
	"shoot_provider":                                                    "Required. OpenStack provider configuration: infrastructure, load-balancer provider, and worker groups. Its infrastructure and load-balancer settings are fixed at creation (see nested attributes); only `workers` are edited in place.",
	"shoot_provider.load_balancer_provider":                             "Required. OpenStack load-balancer provider, e.g. \"amphora\". Fixed at creation — changing it forces the cluster to be recreated.",
	"shoot_provider.infrastructure_config":                              "Required. OpenStack network infrastructure for the cluster. `floating_pool_name` is fixed at creation; `network_id`/`router_id`/`workers_network_cidr` are auto-created and read back when omitted.",
	"shoot_provider.infrastructure_config.floating_pool_name":           "Required. Name of the external floating-IP pool, e.g. \"ext-net\". Fixed at creation — changing it forces the cluster to be recreated.",
	"shoot_provider.infrastructure_config.network_id":                   "OpenStack network UUID. Optional and Computed: omit to let Cleura create a network and write its ID back to state (no replacement). Setting an explicit, different UUID forces the cluster to be recreated.",
	"shoot_provider.infrastructure_config.router_id":                    "OpenStack router UUID. Optional and Computed: omit to let Cleura create a router and write its ID back to state (no replacement). Setting an explicit, different UUID forces the cluster to be recreated.",
	"shoot_provider.infrastructure_config.workers_network_cidr":         "CIDR for the worker node subnet, e.g. \"10.250.0.0/16\". Optional and Computed: omit to let Cleura assign one and write it back (no replacement). Setting an explicit, different value forces the cluster to be recreated.",
	"shoot_provider.workers":                                            "Required. One or more worker node groups. Groups are matched by `name` across plan and state and reconciled per group (updated, added, or removed) in place — this does not recreate the cluster.",
	"shoot_provider.workers.name":                                       "Worker-group name (letters, digits, underscores, hyphens). Optional and Computed (assigned by the API if omitted). Serves as the group's identity: renaming it deletes the old group and creates a new one (node churn for that group), rather than replacing the whole cluster.",
	"shoot_provider.workers.machine":                                    "Required. Machine (node) specification for the group: flavor and OS image.",
	"shoot_provider.workers.machine.type":                               "String, Optional and Computed. OpenStack flavor / instance type for the nodes, e.g. \"b.2c4gb\". API default read back if omitted.",
	"shoot_provider.workers.machine.image_name":                         "String, Optional and Computed. Node OS image name, e.g. \"gardenlinux\". API default read back if omitted.",
	"shoot_provider.workers.machine.image_version":                      "String, Optional and Computed. Node OS image version (numeric, dot-separated), e.g. \"1877.19.0\". API default read back if omitted.",
	"shoot_provider.workers.minimum":                                    "Int64, Optional and Computed. Minimum node count (cluster-autoscaler lower bound). On update the current value is pinned from state when omitted.",
	"shoot_provider.workers.maximum":                                    "Int64, Optional and Computed. Maximum node count (cluster-autoscaler upper bound). On update the current value is pinned from state when omitted.",
	"shoot_provider.workers.max_surge":                                  "Int64, Optional and Computed. Number of extra nodes that may be added above `maximum` during a rolling update. Pinned from state when omitted on update.",
	"shoot_provider.workers.max_unavailable":                            "Int64, read-only (Computed). Number of nodes allowed to be unavailable during a rolling update; defaults to 0 and is not user-configurable (the API value is read back into state).",
	"shoot_provider.workers.volume_size":                                "Required. Root disk size for each node in the group, e.g. \"50Gi\".",
	"shoot_provider.workers.zones":                                      "List of strings, Optional and Computed. OpenStack availability zones the group's nodes are spread across, e.g. [\"nova\"]. Pinned from state when omitted on update.",
	"shoot_provider.workers.labels":                                     "Optional and Computed list of Kubernetes node labels (key/value) applied to the group. Managed exclusively by Terraform: omitting the block clears all labels server-side. Applied in place.",
	"shoot_provider.workers.labels.key":                                 "Required. Label key.",
	"shoot_provider.workers.labels.value":                               "Required. Label value.",
	"shoot_provider.workers.annotations":                                "Optional and Computed list of Kubernetes node annotations (key/value) applied to the group. Managed exclusively by Terraform: omitting the block clears all annotations server-side. Applied in place.",
	"shoot_provider.workers.annotations.key":                            "Required. Annotation key.",
	"shoot_provider.workers.annotations.value":                          "Required. Annotation value.",
	"shoot_provider.workers.taints":                                     "Optional and Computed list of Kubernetes node taints applied to the group. Managed exclusively by Terraform: omitting the block removes all taints server-side. Applied in place.",
	"shoot_provider.workers.taints.key":                                 "Required. Taint key.",
	"shoot_provider.workers.taints.value":                               "Required. Taint value.",
	"shoot_provider.workers.taints.effect":                              "Required. Taint effect; one of \"NoSchedule\", \"NoExecute\", or \"PreferNoSchedule\".",
}
