package provider

import (
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
)

const secretTestPassword = "Sup3rSecret-Passw0rd"

func TestRedactSecret(t *testing.T) {
	for _, tc := range []struct {
		name, text, secret, want string
	}{
		{"removes the secret", `HTTP 400: {"password":"Sup3rSecret-Passw0rd"}`, secretTestPassword, `HTTP 400: {"password":"(redacted)"}`},
		{"removes every occurrence", "a Sup3rSecret-Passw0rd b Sup3rSecret-Passw0rd", secretTestPassword, "a (redacted) b (redacted)"},
		{"leaves unrelated text alone", "HTTP 400: name already in use", secretTestPassword, "HTTP 400: name already in use"},
		{"ignores an empty secret", "HTTP 400: bad request", "", "HTTP 400: bad request"},
		{"ignores a too-short secret", "an error about a", "a", "an error about a"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if got := redactSecret(tc.text, tc.secret); got != tc.want {
				t.Errorf("redactSecret() = %q, want %q", got, tc.want)
			}
		})
	}
}

// echoingHandler answers user creates with a 400 whose body quotes the whole
// submitted payload, the way a validation error commonly does. Everything else
// falls through to the mock.
func echoingHandler(mock *mockIdentity) http.Handler {
	inner := mock.handler()
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method == http.MethodPost && strings.HasSuffix(r.URL.Path, "/users") {
			var body map[string]any
			_ = json.NewDecoder(r.Body).Decode(&body)
			echoed, _ := json.Marshal(body)
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusBadRequest)
			fmt.Fprintf(w, `{"detail":"password does not meet the policy: %s"}`, string(echoed))
			return
		}
		inner.ServeHTTP(w, r)
	})
}

// TestOpenStackUserErrorDoesNotEchoThePassword drives a failing create through
// the real Terraform binary against an API that echoes the request payload in
// its error. The password is write-only, so keeping it out of state is not
// enough: the diagnostic reaches the console and CI logs too.
func TestOpenStackUserErrorDoesNotEchoThePassword(t *testing.T) {
	mock := newMockIdentity()
	srv := httptest.NewServer(echoingHandler(mock))
	t.Cleanup(srv.Close)
	t.Setenv("CLEURA_API_URL", srv.URL)
	t.Setenv("CLEURA_API_USERNAME", mock.username)
	t.Setenv("CLEURA_API_TOKEN", mock.token)

	config := fmt.Sprintf(`
provider "cleura" {
  cloud   = "public"
  region  = "Sto2"
  use_cli = false
}

resource "cleura_openstack_user" "leaky" {
  name                = "tfsec-user"
  password            = %q
  password_wo_version = "1"
}`, secretTestPassword)

	resource.UnitTest(t, resource.TestCase{
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{{
			Config: config,
			// The error must name the failure and show the redaction marker,
			// and must not contain the password itself.
			ExpectError: regexp.MustCompile(`(?s)Failed to create OpenStack user.*\(redacted\)`),
		}},
	})
}

// TestOpenStackUserPasswordStaysOutOfArtifacts asserts the password is absent
// from everything Terraform writes to disk: the state file a customer commits
// by mistake, and the saved plan they hand to a reviewer.
func TestOpenStackUserPasswordStaysOutOfArtifacts(t *testing.T) {
	mock := newMockIdentity()
	srv := httptest.NewServer(mock.handler())
	t.Cleanup(srv.Close)
	t.Setenv("CLEURA_API_URL", srv.URL)
	t.Setenv("CLEURA_API_USERNAME", mock.username)
	t.Setenv("CLEURA_API_TOKEN", mock.token)

	// Pin the framework's scratch root so the scan below covers exactly the
	// files this run wrote: the state, the saved plans and nothing else.
	scanDir := t.TempDir()
	t.Setenv("TF_ACC_TEMP_DIR", scanDir)

	config := fmt.Sprintf(`
provider "cleura" {
  cloud   = "public"
  region  = "Sto2"
  use_cli = false
}

resource "cleura_openstack_user" "secret" {
  name                = "tfsec-user"
  password            = %q
  password_wo_version = "1"
  description         = "secret handling test"
}`, secretTestPassword)

	// Scan every file the working directory holds after the step: state,
	// saved plans and the framework's own scratch files all live there.
	noSecretOnDisk := func(*terraform.State) error {
		sawState := false
		err := filepath.WalkDir(scanDir, func(path string, d os.DirEntry, err error) error {
			if err != nil || d.IsDir() {
				return nil //nolint:nilerr // unreadable entries are not the subject here
			}
			// The .tf files are the configuration the customer wrote; the
			// password is supposed to be there. Everything else in this
			// directory is generated by Terraform, and must not hold it.
			if ext := filepath.Ext(path); ext == ".tf" || ext == ".json" && strings.HasSuffix(path, ".tf.json") {
				return nil
			}
			data, readErr := os.ReadFile(path)
			if readErr != nil {
				return nil //nolint:nilerr
			}
			if strings.Contains(filepath.Base(path), "tfstate") {
				sawState = true
			}
			if strings.Contains(string(data), secretTestPassword) {
				rel, _ := filepath.Rel(scanDir, path)
				return fmt.Errorf("the write-only password was written to %s", rel)
			}
			return nil
		})
		if err != nil {
			return err
		}
		// Without a state file in the scan, a clean result would prove nothing.
		if !sawState {
			return fmt.Errorf("no state file found under the Terraform scratch directory; the scan proved nothing")
		}
		return nil
	}

	resource.UnitTest(t, resource.TestCase{
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{{
			Config: config,
			Check: resource.ComposeAggregateTestCheckFunc(
				resource.TestCheckNoResourceAttr("cleura_openstack_user.secret", "password"),
				resource.TestCheckResourceAttr("cleura_openstack_user.secret", "password_wo_version", "1"),
				noSecretOnDisk,
				func(*terraform.State) error {
					// It did reach the API, so the test is not passing vacuously.
					u := mock.userByName("tfsec-user")
					if u == nil {
						return fmt.Errorf("user was not created")
					}
					if u.Password != secretTestPassword {
						return fmt.Errorf("the API received password %q, want the configured one", u.Password)
					}
					return nil
				},
			),
		}},
	})
}
