// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_cleura

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func CleuraProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type CleuraModel struct {
}
